services:
  mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 27017

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  # Uncomment to use redis
  redis:
     image: redis:7-alpine
     expose:
       - 6379

  api:
    build:
      context: .
      dockerfile: document.e2e.Dockerfile
    env_file:
      - env-example-document
    environment:
      DATABASE_TYPE: mongodb
      DATABASE_URL: mongodb://mongo:${DATABASE_PORT}
      DATABASE_HOST: mongo
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
