# Use postgres/example user/password credentials
version: "3.1"
name: world_of_hex
services:
  db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world_of_hex
    ports:
      - 5423:5432
    volumes:
      - ./.local/db_data:/var/lib/postgresql/world_of_hex

